server:
  port: 3001
  context-path: /

spring:
  application:
    name: microservice-zuul

eureka:
  instance:
    instance-id: microservice-zuul:3001 #\u5BA2\u6237\u7AEF\u5B9E\u4F8B\u540D\u79F0
    prefer-ip-address: true #\u662F\u5426\u663E\u793AIP
  client:
    service-url:
      #\u8BBE\u7F6E\u4E0EEureka\u6CE8\u518C\u4E2D\u5FC3\u4EA4\u4E92\u7684\u5730\u5740\uFF0C\u662F\u6240\u6709\u6CE8\u518C\u4E2D\u5FC3
      defaultZone: http://eureka2001.javawwl.com:2001/eureka/,http://eureka2002.javawwl.com:2002/eureka/,http://eureka2003.javawwl.com:2003/eureka/   #\u628A\u670D\u52A1\u6CE8\u518C\u5230eureka\u6CE8\u518C\u4E2D\u5FC3

zuul:
  routes: # \u6240\u6709\u7684\u8DEF\u7531\u90FD\u8981\u914D\u7F6E\u5728\u8FD9\u91CC
    studentServer.serviceId: microservice-student
    studentServer.path: /studentServer/**
  ignored-services: "*"
  prefix: /javawwl


info:
  groupId: com.liwangwang.springcloud
  artifactId: microservice-zuul-3001
  version: 1.0-SNAPSHOT
  userName: http://www.javawwl.com
  phone: 123456

